name: FreeBSD Release
permissions:
  contents: write

on:
  push:
    tags:
      - "*"
      - "!*-alpha*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
        default: 'v1.0.0'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22.4.1
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          yarn install
          VITE_APP_VERSION=$(git describe --tags) yarn run build
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Build Backend (amd64)
        run: |
          go mod download
          GOOS=freebsd GOARCH=amd64 go build -ldflags "-s -w -X 'one-api/common/config.Version=$(git describe --tags)' -extldflags '-static'" -o one-api-freebsd-amd64

      - name: Build Backend (arm64)
        run: |
          go mod download
          GOOS=freebsd GOARCH=arm64 go build -ldflags "-s -w -X 'one-api/common/config.Version=$(git describe --tags)' -extldflags '-static'" -o one-api-freebsd-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            one-api-freebsd-amd64
            one-api-freebsd-arm64
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GT_Token }} 